name: rickstarbuck
favicon: null
layout_spectrum: 0.29412203072570264
typography_spectrum: 0.3811811967752874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.38066480588167906
  lightness: 0.9249407455790788
  saturation: 0.2927811664994806
  rhythmicContrast: 0.05114959739148617
purpose: []
