name: rickstarbuck
favicon: null
layout_spectrum: 0.29412203072570264
typography_spectrum: 0.20382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7b1a9'
    - '#120907'
    - '#5d363f'
    - '#411c1d'
    - '#91857f'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
